### ISSUE TITLE
gofmtrlx is sometimes too relaxed

### ISSUE THREAD

**Issue by haya14busa** [rhysd/gofmtrlx#2]
### How to reproduce
```
cat << EOF | gofmtrlx
package
func func() {

}
EOF
```

#### Output:
```
package
```

gofmt returns following errors.

```
$ cat << EOF | gofmt -e
package
func func() {

}
EOF
<standard input>:2:1: expected 'IDENT', found 'func'
<standard input>:2:6: expected ';', found 'func'
```

maybe, gofmtrlx should check error messages along with AST errors.
In addition, it's better to outputs errors to stderr.
What do you think?

**Comment by rhysd** [comment]
Thank you for reporting the case.

Your case should be filtered out. I also think we need to look error messages. Next point is which message should be filtered. Do you know there is any way to know the error is lexing error or parsing error from the returned `error` instance from `ParseFile`?

> In addition, it's better to outputs errors to stderr.

As I commented in the golang/go issue, I need to do this and will do soon :+1: Although I'm not sure if exit code should be non-zero or not.

**Comment by rhysd** [comment]
I have two ideas

1. FIltering lexing error by `strings.Contain(err.Error(), "expected '")` or regex
2. Main purpose of this plugin is to allow trailing commas. So only permit `syntax error: unexpected semicolon or newline, expecting comma or }`

I'd like to choose 2. What is your idea?

**Comment by haya14busa** [comment]
So, option 1 is blacklist style and option 2 is whitelist style, right?

I prefer option 2 too.
But, one thing I concerned about is that if we are going to use whitelist style now, we may overlook other useful cases which can be automatically fixed by gofmt correctly.

I think gofmtrlx is still in early period, so we might be able to find other useful cases while using gofmtrlx.
With https://github.com/rhysd/gofmtrlx/commit/f1461b14190ee3e8a3cca46c604e4e99f975cdb3, we could collect parse errors but with no problem for using it as gofmt.

But, as I said above, I prefer option 2, whitelist style in the end. So, I leave it to you.
Maybe, we can just wait fixing this issue a couple of weeks if we can withstand a rare format failure?

**Comment by haya14busa** [comment]
> Although I'm not sure if exit code should be non-zero or not.

I don't expect non-zero exit code for parsing errors which can be ignored as gofmt (e.g. missing trailing comma error). We cannot use gofmtrlx from other tools like editor if it always returns non-zero exit code with parsing error.

**Comment by rhysd** [comment]
yeah... but it's also fact that vim-go`s `:GoFmt` does not show stderr output if exit code is non-zero.

anyway, both ways are not perfect. so I think continuing current behavior is better.

**Comment by rhysd** [comment]
Hmm... I'm not thinking to extend gofmtrlx to another formatter. It should be just *a bit* relaxed gofmt. So, let's say to choose 2. option. :+1:
